### ISSUE TITLE
question about the outputs

### ISSUE THREAD

**Issue by attitudechunfeng** [scarletcho/KoG2P#1]
It seems that the program will never output "ks,nc, nh, lk,lm,lb, ls,lt,lp,lh,ps", am i right?

**Comment by scarletcho** [comment]
Right. The program (g2p.py) will not output any of the listed complex codas in Korean, because they are always simplified into one of the seven phonotactically allowed codas (ㄱ,ㄴ,ㄷ,ㄹ,ㅁ,ㅂ,ㅇ; each represented as kf, nf, tf, ll, mf, pf, ng respectively in KoG2P) after applying the phonological rules in Korean.

**Comment by attitudechunfeng** [comment]
Thanks, i've got it and close this issue.
